# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image:mongo:latest
  volumes:
    -type:volume
      source:configdb
      target:/data/configdb
    -type:volume
      source:db
      target:/data/db
    -type:bind
      source:/Users/rjallen/repos/mongodb/mongod.conf
      target:/etc/mongod.conf
    restart:always
  ports:
    - 27017:27017
  environment:
    MONGO_INITDB_ROOT_USERNAME:root
    MONGO_INITDB_ROOT_PASSWORD:passw0rd


  mongo-express:
    image:mongo-express
    restart:always
  ports:
    - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ME_CONFIG_MONGODB_URL: mongodb://root:passw0rd@localhost:27017/


  volumes:
    configdb:
    db:
